# -*- coding: utf-8 -*-
"""f4_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19sZTRuiyH69sjrsIL9jeQkoDLQjwwpYQ
"""

import time
import threading
import requests

def read_example() -> None:
  response = requests.get('https://www.example.com')
  print(response.status_code)
thread_1 = threading.Thread(target=read_example)
thread_2 = threading.Thread(target=read_example)
thread_start = time.time()
thread_1.start()
thread_2.start()
print('Все потоки работают!')
thread_1.join()
thread_2.join()
thread_end = time.time()
print(f'Многопоточное выполнение заняло {thread_end - thread_start:.4f} с.')

